### ISSUE TITLE
Add cli support

### ISSUE THREAD

**Issue by vicky-gonsalves** [vicky-gonsalves/deno_rest#2]
To enhance this boilerplate further add support for cli toolkit, which will act as a project generator and will be easier to maintain its features.

**Comment by vicky-gonsalves** [comment]
**TODO** 

- [x] Initial scaffolding generation
- [ ] Controller generation command 
- [ ] Model generation command
- [ ] Service generation command
- [ ] Validation generation command
- [ ] Auto unit tests generation
- [ ] Auto integration tests generation
